# encoding: UTF-8
#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: on
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[thrashmaster::default]
  driver:
    publish_all: true
    hostname: chef.mudbox.dev
    forward:
      - 80
      - 443
