
source 'https://supermarket.getchef.com'

group :community do
  cookbook '7-zip'
  cookbook 'apache2'
  cookbook 'apt'
  cookbook 'ark'
  cookbook 'aufs'
  cookbook 'bluepill'
  cookbook 'build-essential'
  cookbook 'chef-client'
  cookbook 'chef-dk'
  cookbook 'chef-sugar'
  cookbook 'chef_handler'
  cookbook 'chruby_install'
  cookbook 'cron'
  cookbook 'device-mapper'
  cookbook 'dmg'
  cookbook 'docker'
  cookbook 'dpkg_autostart'
  cookbook 'git'
  cookbook 'golang'
  cookbook 'homebrew'
  cookbook 'htpasswd'
  cookbook 'iptables'
  cookbook 'iptables-ng'
  cookbook 'java'
  cookbook 'jenkins'
  cookbook 'logrotate'
  cookbook 'lxc'
  cookbook 'modules'
  cookbook 'nginx'
  cookbook 'nginx-proxy'
  cookbook 'nodejs'
  cookbook 'ntp'
  cookbook 'ohai'
  cookbook 'openssl'
  cookbook 'os-hardening'
  cookbook 'packagecloud'
  cookbook 'polipo'
  cookbook 'postgresql'
  cookbook 'python'
  cookbook 'redisio'
  cookbook 'resolver'
  cookbook 'rsyslog'
  cookbook 'rubies'
  cookbook 'ruby_install'
  cookbook 'runit'
  cookbook 'ssh-hardening'
  cookbook 'sudo'
  cookbook 'supermarket'
  cookbook 'sysctl'
  cookbook 'ulimit'
  cookbook 'windows'
  cookbook 'yum'
  cookbook 'yum-epel'
end

cookbook 'garcon',     github: 'riddopic/garcon', branch: 'develop'
cookbook 'pipeline',   git:    'git@github.com:riddopic/pipeline.git'
